[tool.poetry]
name = "coral-inference"
version = "0.1.0"
description = ""
authors = ["zhaokefei <zhaokefei@tezign.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "<3.12,>=3.8"
scipy = "1.10.0"
inference="^0.16.2"
inference-gpu = {version = "^0.16.2", optional = true}
rknn-toolkit-lite2 = {version = "^1.6.0", optional = true, platform = "aarch64", source = "loopeai"}


[tool.poetry.extras]
gpu = ["inference-gpu"]
npu = ["rknn-toolkit-lite2"]

[[tool.poetry.source]]
name = "tsinghua"
url = "https://pypi.tuna.tsinghua.edu.cn/simple"
priority = "default"

[[tool.poetry.source]]
name = "loopeai"
url = "http://pypi.loopeai.com/simple"
priority = "supplemental"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
