import os

CORAL_PLATFORM_BASE_URL = "https://coral.loopeai.com"
CORAL_LICENSE_SERVER_HOST = "coral.loopeai.com"
CORAL_METRICS_URL = f"{CORAL_PLATFORM_BASE_URL}/inference-stats"


def apply_runtime_default_backend_env() -> None:
    os.environ.setdefault("API_BASE_URL", CORAL_PLATFORM_BASE_URL)
    os.environ.setdefault("LICENSE_SERVER", CORAL_LICENSE_SERVER_HOST)
    os.environ.setdefault("METRICS_URL", CORAL_METRICS_URL)


# 当前运行的环境
CURRENT_INFERENCE_PLATFORM = os.getenv("CURRENT_INFERENCE_PLATFORM")

# InfluxDB 指标上报相关环境变量
# 说明：InfluxDB3 Core 使用简化的配置，只需要 URL、TOKEN、DATABASE
# 若未配置，将在使用时关闭指标写入并打印告警日志
INFLUXDB_METRICS_URL = os.getenv("INFLUXDB_METRICS_URL")
INFLUXDB_METRICS_TOKEN = os.getenv("INFLUXDB_METRICS_TOKEN")
INFLUXDB_METRICS_DATABASE = os.getenv("INFLUXDB_METRICS_DATABASE")
INFLUXDB_METRICS_PORT = os.getenv("INFLUXDB_METRICS_PORT")

# CoralReef Backend runtime package contract
CORAL_BACKEND_INTERNAL_SECRET = os.getenv("CORAL_BACKEND_INTERNAL_SECRET")
CORAL_BACKEND_PACKAGE_TIMEOUT = float(
    os.getenv("CORAL_BACKEND_PACKAGE_TIMEOUT", "60")
)

# INFERENCE_SERVER_ID
# DEVICE_ID
# MODEL_CACHE_DIR
# METRICS_URL
# LICENSE_SERVER
# API_BASE_URL
# ROBOFLOW_SERVER_UUID
