import os

# 当前运行的环境
CURRENT_INFERENCE_PLATFORM = os.getenv("CURRENT_INFERENCE_PLATFORM")

# INFERENCE_SERVER_ID
# DEVICE_ID
# MODEL_CACHE_DIR
# METRICS_URL
# LICENSE_SERVER
# API_BASE_URL
# ROBOFLOW_SERVER_UUID
