import os

# 当前运行的环境
CURRENT_INFERENCE_PLATFORM = os.getenv("CURRENT_INFERENCE_PLATFORM")

# InfluxDB 指标上报相关环境变量
# 说明：InfluxDB3 Core 使用简化的配置，只需要 URL、TOKEN、DATABASE
# 若未配置，将在使用时关闭指标写入并打印告警日志
INFLUXDB_METRICS_URL = os.getenv("INFLUXDB_METRICS_URL")
INFLUXDB_METRICS_TOKEN = os.getenv("INFLUXDB_METRICS_TOKEN")
INFLUXDB_METRICS_DATABASE = os.getenv("INFLUXDB_METRICS_DATABASE")

# INFERENCE_SERVER_ID
# DEVICE_ID
# MODEL_CACHE_DIR
# METRICS_URL
# LICENSE_SERVER
# API_BASE_URL
# ROBOFLOW_SERVER_UUID
