name: Build and Push CPU Containers

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  release:
    types: [created]
  push:
    branches:
      - 'main'
      - 'dev'
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      force_push:
        type: boolean
        description: "Do you want to push image after build?"
        default: false

jobs:
  docker-cpu:
    uses: ./.github/workflows/reusable-docker-build.yml
    with:
      image-type: cpu
      dockerfile-path: ./docker/dockerfiles/Dockerfile.cpu
      platforms: linux/arm64,linux/amd64
      push-image: ${{ github.event_name == 'release' || github.event_name == 'push' || inputs.force_push }}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
