name: Build and Push Rknn Containers

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  release:
    types: [created]
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      force_push:
        type: boolean
        description: "Do you want to push image after build?"
        default: false

env:
  RKNN_VERSION: "1.6.0"
  DOCKER_BUILDKIT: 1
  BUILDKIT_INLINE_CACHE: 1

jobs:
  docker-rknn:
    uses: ./.github/workflows/reusable-docker-build.yml
    with:
      image-type: rknn
      dockerfile-path: ./docker/dockerfiles/Dockerfile.rknn
      push-image: ${{ github.event_name == 'release' || github.event_name == 'push' || inputs.force_push }}
      build-args: |
        --cache-from=type=gha
        --cache-to=type=gha,mode=max
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
