name: Build and Push GPU Containers

permissions:
  contents: read
  packages: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      force_push:
        type: boolean
        description: "Do you want to push image after build?"
        default: false
      custom_tag:
        type: string
        description: "Custom tag to use for the image (overrides VERSION)"
        default: ""

jobs:
  docker-gpu:
    uses: ./.github/workflows/reusable-docker-build.yml
    with:
      image-type: gpu
      dockerfile-path: ./docker/dockerfiles/Dockerfile.gpu
      platforms: linux/amd64
      push-image: ${{ startsWith(github.ref, 'refs/tags/') || inputs.force_push }}
      custom_tag: ${{ inputs.custom_tag }}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
