name: Build and Push CPU Containers

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  release:
    types: [created]
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      force_push:
        type: boolean
        description: "Do you want to push image after build?"
        default: false

env:
  DOCKER_BUILDKIT: 1
  BUILDKIT_INLINE_CACHE: 1

jobs:
  docker-cpu:
    uses: ./.github/workflows/reusable-docker-build.yml
    with:
      image-type: cpu
      cache-path: /tmp/.cpu-buildx-cache
      dockerfile-path: ./docker/dockerfiles/Dockerfile.cpu
      push-image: ${{ github.event_name == 'release' || github.event_name == 'push' || inputs.force_push }}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
