name: Build and Push CPU Containers

permissions:
  contents: read
  packages: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - 'main'
      - 'dev'
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      force_push:
        type: boolean
        description: "Do you want to push image after build?"
        default: false
      custom_tag:
        type: string
        description: "Custom tag to use for the image (overrides VERSION)"
        default: ""
      registry:
        type: choice
        description: 'Docker Registry'
        default: 'docker.io'
        options:
          - 'docker.io'
          - 'ghcr.io'
          - 'custom'
      custom_registry:
        type: string
        description: 'Custom registry URL (if registry is custom)'
        default: ''

jobs:
  docker-cpu:
    uses: ./.github/workflows/reusable-docker-build.yml
    with:
      image-type: cpu
      dockerfile-path: ./docker/dockerfiles/Dockerfile.cpu
      platforms: linux/arm64,linux/amd64
      push-image: ${{ startsWith(github.ref, 'refs/tags/') || inputs.force_push }}
      custom_tag: ${{ inputs.custom_tag }}
      registry: ${{ inputs.registry || 'docker.io' }}
      custom_registry: ${{ inputs.custom_registry }}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      DOCKERHUB_REGISTRY: ${{ secrets.DOCKERHUB_REGISTRY }}
      GHCR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
